project:
  title: "Portfolio SIG"
  output-dir: docs/es

website:
  site-url: https://cdbyl.github.io/portfolio/es
  description: "Portfolio de Carolina Byl"
  favicon: loguito.png
  open-graph:
    locale: es_ES
  twitter-card:
    creator: "@cdbyl"
  navbar:
    pinned: true
    left:
      # - text: "Home"
      #   href: index.html
      - text: "Portfolio"
        href: projects-es.html
      #- text: "Blog"
      #  href: blog.html
      #- icon: rss
      #  href: blog.xml
#comentado pero hay que descomentar cuando habilite la versión en español
    # right:
    #   - text: "Español"
    #     href: ../es/
  page-footer:
    left: "Sitio creado con Quarto"

lang: es
